#!/bin/bash

# Credits for this script go to laheller
# https://github.com/gphoto/libgphoto2/issues/335#issuecomment-881946081

set -x
set -e

REPO_NAME=libgphoto2
REPO_URL=https://github.com/gphoto/libgphoto2
# REPO_URL=https://github.com/sszllxos/libgphoto2

export CONFIGURE_ARGS="camlibdir=/data/data/com.sszllx.knativecanon/cache"
# export BRANCH="-b camera_detected"

/scripts/build-generic $REPO_NAME $REPO_URL $BINARY_PATH

# cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2_port.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
# cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
