#!/bin/bash

CODEPATH=/data/code
# CODEPATH=/exdata3/lijing/code

cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2_port.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libusb-1.0.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libexif.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libltdl.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libpopt.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
