#!/bin/bash

# 获取本机所有 IP 地址
IP_ADDRESSES=$(hostname -I)

# 判断是否包含 10.67
if echo "$IP_ADDRESSES" | grep -q "10.67"; then
    CODEPATH="/data/code"
else
    CODEPATH="/exdata3/lijing/code"
fi

cp ${CODEPATH}/workspace/_prefix/lib/libgphoto2_port.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp ${CODEPATH}/workspace/_prefix/lib/libgphoto2.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp ${CODEPATH}/workspace/_prefix/lib/libusb-1.0.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp ${CODEPATH}/workspace/_prefix/lib/libexif.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp ${CODEPATH}/workspace/_prefix/lib/libltdl.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp ${CODEPATH}/workspace/_prefix/lib/libpopt.so ${CODEPATH}/knativecanon/app/src/main/cpp/libs/arm64-v8a/
