#!/bin/bash

cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2_port.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libgphoto2_port/0.12.2/usb1.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
cp /exdata3/lijing/code/workspace/_prefix/lib/libusb-1.0.so /exdata3/lijing/code/knativecanon/app/src/main/cpp/libs/arm64-v8a/
